name: Update Data

on:
  schedule:
    - cron: '45 9 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python fetch.py

      - name: Commit data
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@mail.com"
          git add data.json
          git commit -m "auto update" || echo "no change"
          git push
